// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBebBrHrmRtr0RRamw7Cv2B-bdwldD2Toc',
    appId: '1:993342818538:web:4edc5df4875909ab626f93',
    messagingSenderId: '993342818538',
    projectId: 'troiacode17',
    authDomain: 'troiacode17.firebaseapp.com',
    storageBucket: 'troiacode17.firebasestorage.app',
    measurementId: 'G-51JVLC8J9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIPm6MdMrzkdHeT3WvFRtkl_LwqlnDOs',
    appId: '1:993342818538:android:55891344cf58f6ef626f93',
    messagingSenderId: '993342818538',
    projectId: 'troiacode17',
    storageBucket: 'troiacode17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJv2YLeRi7Fk386EqD1f8xgkVFJCotnf8',
    appId: '1:993342818538:ios:4fb08de574c2da98626f93',
    messagingSenderId: '993342818538',
    projectId: 'troiacode17',
    storageBucket: 'troiacode17.firebasestorage.app',
    iosBundleId: 'com.example.troiacode17',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJv2YLeRi7Fk386EqD1f8xgkVFJCotnf8',
    appId: '1:993342818538:ios:4fb08de574c2da98626f93',
    messagingSenderId: '993342818538',
    projectId: 'troiacode17',
    storageBucket: 'troiacode17.firebasestorage.app',
    iosBundleId: 'com.example.troiacode17',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBebBrHrmRtr0RRamw7Cv2B-bdwldD2Toc',
    appId: '1:993342818538:web:9bfa95892dace321626f93',
    messagingSenderId: '993342818538',
    projectId: 'troiacode17',
    authDomain: 'troiacode17.firebaseapp.com',
    storageBucket: 'troiacode17.firebasestorage.app',
    measurementId: 'G-WJ1WF3GZ5P',
  );
}
